### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by nga-hoeun** [nga-hoeun/2022-QUIZ-APP-G15#1]
Layout of the app

**Comment by mengyer34** [comment]
![6](https://user-images.githubusercontent.com/90229183/150482957-c325c608-fff1-4a76-8c09-f33e90ed7412.png)
![7](https://user-images.githubusercontent.com/90229183/150482964-d255cc0b-c707-4701-ae08-c92ecbf89670.png)
![1](https://user-images.githubusercontent.com/90229183/150482967-be0faa3b-707a-478f-9ac0-23503dc0d934.png)
![2](https://user-images.githubusercontent.com/90229183/150482968-b06819bf-d2e3-4794-bcd0-cf93007ea2e0.png)
![3](https://user-images.githubusercontent.com/90229183/150482971-cc41f274-279f-43dc-aab5-dea01253ed09.png)
![4](https://user-images.githubusercontent.com/90229183/150482972-3fd00c1c-ebd9-435a-a4d4-e81009a5d272.png)
![5](https://user-images.githubusercontent.com/90229183/150482973-75f7c42a-fdad-4044-a1d1-0540c554fb21.png)

**Comment by mengyer34** [comment]
![1](https://user-images.githubusercontent.com/90229183/150483135-e3172ca3-4b8d-43ec-a167-0a5c0e95d11d.png)
![4](https://user-images.githubusercontent.com/902
![7](https://user-images.githubusercontent.com/90229183/150483196-6cc2738b-0159-488e-add0-e8acd671e7d9.png)

![6](https://user-images.githubusercontent.com/90229183/150483191-fa6a4346-75c8-418c-b672-ee4c86682f53.png)

![5](https://user-images.githubusercontent.com/90229183/150483182-1a6ff82a-48b1-46eb-bc5f-247753b4aa94.png)
29183/150483171-ed3fd257-01c3-45da-8587-cbddd606b69f.png)

![2](https://user-images.githubusercontent.com/90229183/150483151-f036499f-df4b-4bc0-9c79-75fbdfccb977.png)
![3](https://user-images.githubusercontent.com/90229183/150483157-85dd9d58-4a5b-43b2-a6fe-2d3c4fcf5dfa.png)

**Comment by mengyer34** [comment]
![1](https://user-images.githubusercontent.com/90229183/150483391-07c7dabe-cadf-4720-88aa-8e5afe150f38.png)
![2](https://user-images.githubusercontent.com/90229183/150483401-d090fdaa-ada5-404a-be12-261949999a3c.png)
![3](https://user-images.githubusercontent.com/90229183/150483416-aff8b752-4605-404d-adce-f5580b5be8c0.png)
![4](https://user
![5](https://user-im
![6](https://user-images.githubusercontent.com/90229183/150483479-eb557e0c-3865-44dd-a4e3-9b4b24a40b50.pn
![7](https://user-images.githubusercontent.com/90229183/150483486-d875a106-5b86-46f0-ba8a-922c7569a559.png)
g)
ages.githubusercontent.com/90229183/150483473-c1ef97df-2362-468d-b5af-87b0a9a4a66b.png)
-images.githubusercontent.com/90229183/150483459-84749722-1c26-43f7-ba9d-6f49600c9444.png)

**Comment by mengyer34** [comment]
![1](https://user-images.githubusercontent.com/90229183/150483591-b6a3a37c-5a70-46fa-ba2f-3725368ad5ca.png)
![2](https://user-images.githubusercontent.com/90229183/150483609-3cddb1c0-342e-4df8-9066-1f9076044073.png)
![3](https://user-images.githubusercontent.com/90229183/150483615-fa4cef0e-fe14-4308-8e94-79466c747656.png)
![4](https://user-images.githubusercontent.com/90229183/150483631-4cd8c95c-d8f2-4cc9-ae8d
![5](https://user-images.githubusercontent.com/90229183/150483647-5621daf6-ae82-4760-b8ef-fd75a072a659.png)
-65922dacbe6c.png)
![6](https://user-images.githubusercontent.com/90229183/150483678-2178030b-af19-4e4c-b9c6-f4c2947414ec.png)
![7](https://user-images.githubusercontent.com/90229183/150483709-ca41590e-067f-4f7e-997a-f91846def1ce.png)

**Comment by nga-hoeun** [comment]
![1](https://user-images.githubusercontent.com/93235446/150484104-d352eddf-2d74-4ab2-bacb-ee3d2d61cf26.png)

**Comment by nga-hoeun** [comment]
![1](https://user-images.githubusercontent.com/93235446/150484188-48621efe-c85a-44cd-9f59-0943a673b068.png)
![2](https://user-images.githubusercontent.com/93235446/150484198-1685628b-f283-4c1c-ba65-9b6907f4ed2f.png)
![3](https://user-images.githubusercontent.com/93235446/150484207-e2ac06ff-b400-485a-8f9e-99c3ef194ffc.png)
![4](https://user-images.githubusercontent.com/93235446/150484216-33d809c8-bb3a-45a8-be91-33e114998bce.png)
![5](https://user-images.githubusercontent.com/93235446/150484225-4771ae0f-ff6a-4ec2-92d8-59cb9a4d5314.png)
![6](https://user-images.githubusercontent.com/93235446/150484238-bdeb88bb-8f40-4fb1-9ca1-df863cde8b2a.png)
![7](https://user-images.githubusercontent.com/93235446/150484400-3339df1a-d4c7-409b-848b-8291edab9e2b.png)
