### ISSUE TITLE
[Edit view Add a question

### ISSUE THREAD

**Issue by nga-hoeun** [nga-hoeun/2022-QUIZ-APP-G15#2]
Create new questions

**Comment by ronanpnc** [comment]
Add answer form should be composed of 4 textifed

**Comment by ronanpnc** [comment]
The form should ctains 2 buttons
 - CREATE
 - CANCEL

**Comment by ronanpnc** [comment]
![image](https://user-images.githubusercontent.com/67727245/151292964-42bc5d05-9b16-422d-9609-e1f718d2b8a7.png)

**Comment by mengyi-dev** [comment]
fixed
