### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by nga-hoeun** [nga-hoeun/2022-QUIZ-APP-G15#4]
Quiz and edit bar

**Comment by ronanpnc** [comment]
change navigaiton menu
   "Edit the quiz"

**Comment by ronanpnc** [comment]
Be clear on where you are in the navation (PLAY quiz or EDIT quiz)

![image](https://user-images.githubusercontent.com/67727245/151292760-b199a78b-6fd4-4c58-9ffe-be40e7cd42ba.png)

**Comment by mengyi-dev** [comment]
Fixed
