### ISSUE TITLE
[Edit view Validation Input

### ISSUE THREAD

**Issue by nga-hoeun** [nga-hoeun/2022-QUIZ-APP-G15#6]
Message for empty input

**Comment by ronanpnc** [comment]
Disable the button if the question is not valid:
- the 4 answer must be entered
- all question are different
- the good answer must be hoosed


![image](https://user-images.githubusercontent.com/67727245/151293682-19f525e2-164f-49c5-9676-007c8aafa9c1.png)

**Comment by mengyi-dev** [comment]
fixed

**Comment by ronanpnc** [comment]
you should help more the user to fix the errors
